version: "2"

services:
  nginx:
    image: nginx:1.11-alpine
    links: ["php:php"]
    ports: ["8080:80"]
    volumes:
      - ../ec-cube:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/server.conf:/etc/nginx/conf.d/default.conf

  php:
    build: php
#    ports: ["8080:9000"]
    expose: ["9000"]
    command: php-fpm
    links: ["postgres:postgres"]
    volumes:
      - ../ec-cube:/var/www/html
      - ./php/php-fpm.conf:/etc/php5/php-fpm.conf:ro
      - ./php/.user.ini:/etc/php5/conf.d/.user.ini:ro

  postgres:
    image: smizy/postgres
    expose: ["5432"]
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
    environment: 
      - POSTGRES_PASSWORD=mysecretpassword